services:
  bentopdf:
    # simple mode - ghcr.io/mafridi143/bentopdf-simple:latest
    # default mode - ghcr.io/mafridi143/bentopdf:latest
    image: ghcr.io/mafridi143/bentopdf-simple:latest
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - '8080:8080'
